FROM node:18.18.2-alpine AS builder

WORKDIR /app
RUN npm install -g pnpm
COPY . .
RUN pnpm i
RUN pnpm build-storybook

FROM nginx:1.21.3-alpine AS runner
COPY --from=builder /app/storybook-static /usr/share/nginx/html
